language: python
python: '3.8'
os: linux
dist: xenial

install:
  - pip3 install --upgrade setuptools wheel pkgconfig
  - pip3 install https://github.com/PEtab-dev/libpetab-python/archive/develop.zip

# run tests
script:
 - cd Benchmark-Models/
 - ./checkBenchmarkModels.py

# cache dependencies
cache: pip

